name: flutter_starter
description: Use this template to start up a new flutter project
version: 0.0.0
author: cpuccino
homepage: https://github.com/cpuccino/flutter_starter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
